### ISSUE TITLE
Creating account for hosted exchange 2010 fails to parse response

### ISSUE THREAD

**Issue by AdriVanHoudt** [contextio/ContextIO-node#24]
```js
Debug: internal, implementation, error 
    SyntaxError: Uncaught error: Unexpected token I
    at Object.parse (native)
    at IncomingMessage.<anonymous> (.../node_modules/contextio/lib/ContextIO.js:188:26)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at instrumented (.../node_modules/opbeat/lib/instrumentation/async-hooks.js:19:23)
   at doNTCallback2 (node.js:441:9)
   at process._tickDomainCallback [as _tickCallback] (node.js:396:17)
```
As far as we can tell this only happens on a specific hosted exchange 2010 account but since we do not have the credentials we cannot test this. Should I also send a mail to support?

**Comment by cecyc** [comment]
This was an issue specifically with how the API parsed the characters `\I` in the user's label. We deployed a fix for this yesterday and the issue seems to be fixed now.
