### ISSUE TITLE
401 on PUT message

### ISSUE THREAD

**Issue by cdupoiron** [contextio/ContextIO-node#35]
Hello, I receive error on Message API CALL : 

```
var ctxioClient = ContextIO({
    key: config.contextio.key,
    secret: config.contextio.secret,
    version: config.contextio.version
  });
  //PUT https://api.context.io/lite/users/ID/email_accounts/LABEL/folders/FOLDER/messages
  ctxioClient.users(config.contextio.userId)
    .email_accounts(config.contextio.label)
    .folders(config.contextio.inboxFolder)
    .messages(message.message_id)
    .put({ new_folder_id: ANOTHERFOLDER })
    .then(function (ctxioClientRes) {
      res.json(ctxioClientRes);
    });
```

```

/*
 * The error Stack :
Unhandled rejection StatusCodeError: 401 - {"type":"error","code":105,"value":"Invalid signature \/f9Qf7YEq44qY8CVmpLKtDperlM=. Signature base string should be PUT&https%3A%2F%2Fapi.context.io%2Flite%2Fusers%USERID%2Femail_accounts%2Fcontenu%2540EMAIL%253A%253ASMTP%2Ffolders%2FINBOX%2Fmessages%2F%MESSAGEID%2540%253E%2F&oauth_consumer_key%%26oauth_nonce%%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%%26oauth_version%3D1.0"}
    at new StatusCodeError (/home/charles/dev/komunity-app-web/node_modules/request-promise/lib/errors.js:26:15)
    at Request.RP$callback [as _callback] (/home/charles/dev/komunity-app-web/node_modules/request-promise/lib/rp.js:68:32)
    at Request.self.callback (/home/charles/dev/komunity-app-web/node_modules/request-promise/node_modules/request/request.js:186:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/home/charles/dev/komunity-app-web/node_modules/request-promise/node_modules/request/request.js:1081:10)
    at emitOne (events.js:90:13)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/home/charles/dev/komunity-app-web/node_modules/request-promise/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:273:16)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (node.js:383:13)
*/
```

**Comment by AaronLaBrie** [comment]
I've been able to reproduce this one, gonna poke around and see what I can find. Thanks!

**Comment by AaronLaBrie** [comment]
We've identified the issue and are working on a fix. Stay tuned!

**Comment by dado3212** [comment]
Did this get fixed?  I'm still running into this issue.

**Comment by AaronLaBrie** [comment]
@dado3212 I think this is a separate issue. This one was a signing issue on the server, wasn't actually related to this lib.

**Comment by dado3212** [comment]
You can recreate it by sending new_folder_id in the body parameter of a put request (as described in #43).

**Comment by AaronLaBrie** [comment]
Yes, and I am investigating that issue. However, these are not the same.
This issue was a `401` reporting that the oauth signature was invalid.
That issue is a `400` reporting that a required parameter is missing.

**Comment by dado3212** [comment]
The API requires the new_folder_id to be included as a query string parameter.  If it's instead as a form variable, it throws a 401 oauth error.  If there's no form variable but no query string parameter, it 400's.  The issue arises because the default .put({ new_folder_id: folder }) sets the form variable, not the query string parameter.

**Comment by AaronLaBrie** [comment]
Let's keep the discussion over on https://github.com/contextio/ContextIO-node/issues/43 for now.
