### ISSUE TITLE
400 on new_folder_id PUT

### ISSUE THREAD

**Issue by dado3212** [contextio/ContextIO-node#43]
```javascript
ctxioClient
  .users(userID)
  .email_accounts(inboxLabel)
  .folders('INBOX')
  .messages(messageID)
  .put({
    new_folder_id: folder,
  }).then(res => {
    console.log(res);
  });
```
is throwing the below error even though the value is there:

```
Unhandled rejection StatusCodeError: 400 - "{\"type\":\"error\",\"value\":\"new_folder_id is required\"}"
    at new StatusCodeError (/var/www/alexbeals.com/public_html/projects/victor/node_modules/contextio/node_modules/request-promise/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/var/www/alexbeals.com/public_html/projects/victor/node_modules/contextio/node_modules/request-promise/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/var/www/alexbeals.com/public_html/projects/victor/node_modules/contextio/node_modules/request-promise/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/var/www/alexbeals.com/public_html/projects/victor/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/var/www/alexbeals.com/public_html/projects/victor/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/var/www/alexbeals.com/public_html/projects/victor/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

Including the dictionary as the second parameter causes the same error as #35.

**Comment by dado3212** [comment]
The fix is below.  In the put command, you need to first pass an empty dictionary so that the body variable is set to null.  This isn't described anywhere, and doesn't seem like intended functionality.

```javascript
ctxioClient
  .users(userID)
  .email_accounts(inboxLabel)
  .folders('INBOX')
  .messages(messageID)
  .put({}, {
    new_folder_id: folder,
  }).then(res => {
    console.log(res);
  });
```

**Comment by AaronLaBrie** [comment]
@dado3212 Sorry I missed this yesterday, let me take a look.

**Comment by AaronLaBrie** [comment]
Good news: you're right, that is a query parameter not a body parameter.
Bad news: you're right, that was very difficult to figure out from both the api documentation and the documentation for this library.

I'll beef up the section about params in the README here, and see about updating the API docs to specify how data is to be passed.

This isn't a bug, per-say, but it is pretty crummy. Thanks for letting us know!

**Comment by AaronLaBrie** [comment]
Hey @dado3212. Wanted to let you know that I've updated the README here to be more explicit, and I've gone and updated our [main api docs](https://docs.context.io/) to be much clearer about how call params work. I'm gonna close this issue for now, hopefully that helps.
