### ISSUE TITLE
Parse error for Attachment download API call

### ISSUE THREAD

**Issue by VeereshDigasangi** [contextio/ContextIO-node#46]
Hi,
I'm getting error on attachments download API call using node module 'contextio'
For the testing purpose I changed in node_modules/contextio/lib/call-service.js file  where there is a JSON.parse is happening. 
For downloading/getting binary data by attachements api call through node module is not able to parse and it is not need to parse the data.
**API call:** 
 ctxioClient.users(input.id).email_accounts(input.label).folders(input.folder).messages(input.message_id).attachments().get({}).
**Here is the stacktrace:**
SyntaxError: Unexpected token % in JSON at position 0
    at JSON.parse (<anonymous>)
    at sendRequest.then.body (/home/veeresh/FlowRepo/newflow/backend/backend-services/engine/node_modules/contextio/lib/call-service.js:57:21)
    at tryCatcher (/home/veeresh/FlowRepo/newflow/backend/backend-services/engine/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/veeresh/FlowRepo/newflow/backend/backend-services/engine/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/veeresh/FlowRepo/newflow/backend/backend-services/engine/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/veeresh/FlowRepo/newflow/backend/backend-services/engine/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/veeresh/FlowRepo/newflow/backend/backend-services/engine/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/veeresh/FlowRepo/newflow/backend/backend-services/engine/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/veeresh/FlowRepo/newflow/backend/backend-services/engine/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/veeresh/FlowRepo/newflow/backend/backend-services/engine/node_modules/bluebird/js/release/async.js:17:14)

**Comment by AaronLaBrie** [comment]
Hello! For the attachments call you probably want to be using `getFile` instead of `get`, which does not json parse the bodies ([response shape](https://github.com/contextio/ContextIO-node#downloading-files)).

I'll add a note about that to the Readme, since it's not actually mentioned anywhere.

Hope that helps!

**Comment by VeereshDigasangi** [comment]
Thank you for your reply.
If it's like that then why it's supporting attachment call?
If it is throwing error from node module it should properly tested and
verified.
I'll get back to you after trying the getFile call.

**Comment by cecyc** [comment]
Closing as this is not an actual issue with the library.
